- id: gdlint
  name: gdlint
  description: "gdlint - linter for GDScript"
  entry: gdlint
  language: python
  language_version: python3
  additional_dependencies: [setuptools]
  require_serial: true
  types: [gdscript]
- id: gdformat
  name: gdformat
  description: "gdformat - formatter for GDScript"
  entry: gdformat
  language: python
  language_version: python3
  additional_dependencies: [setuptools]
  require_serial: true
  types: [gdscript]
