language: python

jobs:
  include:
    - os: linux
      python: "3.7"
    - os: linux
      python: "3.8"
    - os: linux
      python: "3.9"
    - os: osx
      osx_image: xcode11.2
      language: shell
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: "__token__"
        password:
          secure: mlV3glr9RoEC8vtxE9M7vRrsXD4W1KE8LDowGefLg+QMW6OA5BSikqZFeSWckp4fgU1CgMkn2MzAOMCb2gHn5eDk//oa3th+4VSHdt3jOIgNGbger538zCmQJ+upUy+GEt4ytSURelSoFtDNNdBVMgYr+bP3+vJlwN4qmD4PeUNVv6HUXteq4z62dpg/38ZaovkY8rlasb1h3UJ+lPuwPdzk/lpe0ZwGpwgNj2ftZSj2VEPs9ftBO9n/D1ryDPc+elesPwMUkDanmuLpDZ//8ADvE6XBMAPUK9hyW3e2CSp3TT+3UKA3h4kEXazd9hYH71gCMUPW5ZoeIt2YUa2lJhob3sT68VCbHFe5C81Hc/4os3F/T22mxEul4xT0rAX0wbaNLj1IwnP9NrgmfsnXuY8scI0QLjrGdK2R8yRV008H1OmbfyoEH+3fYijmb4iXWdCGhu/R6sikNbmaN2qY21NVfz5NS0USMDBSkX5sYrOCkSJBPCagpHFby8NI0sxPi4GWq9dlIdYDHPB0QDaSLKGJD4oEq7p0cuFQ18mLmhGjYEYOkhpGQBeoqgKO4IEAtFfRY2GPp/8Reci8PSa4UJP75pMPmdbGCQeU2afEDik2mMcncRXpBhPADUT8dpLAbM9emIoCD6J/Jxar3lTh0gC8lM60xAkXal4lPINdYbs=
        on:
          tags: true
          branch: master

install:
  - pip3 install tox

script:
  - tox
