enum { SOME_A, SOME_B, SOME_C, SOME_D = 789, SOME_E = 123, SOME_F, SOME_G, SOME_H, SOME_I, SOME_J = 9 }
enum Named { SOME_A, SOME_B, SOME_C, SOME_D = 789, SOME_E = 123, SOME_F, SOME_G, SOME_H, SOME_I = 999 }
enum { SOME_XA, SOME_XB, SOME_XC, SOME_XD = 789, SOME_XE = 123, SOME_XF, SOME_XG, SOME_XH, SOME_XI, SOME_XJ = 9 }
enum NamedX { SOME_XA, SOME_XB, SOME_XC, SOME_XD = 789, SOME_XE = 123, SOME_XF, SOME_XG, SOME_XH, SOME_XI = 999 }
